# Generated by Django 5.1.4 on 2024-12-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='close',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='high',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='low',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='stockdata',
            old_name='open',
            new_name='open_price',
        ),
    ]
