# Generated by Django 5.1.4 on 2024-12-15 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_delete_newssource_rename_close_stockdata_close_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
